### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by xyf2002** [harryhanYuhao/aformatter#1]
There miss a space between "global" and "start"

**Comment by xyf2002** [comment]
as example.asm
example.asm: Assembler messages:
example.asm:1: error：unknown pseudo-op: `.global_start'
example.asm:45: error：junk at end of line, first unrecognized character is `H'

**Comment by harryhanYuhao** [comment]
resolved in commit 7b64090711d7807df1a31cae0741e6d09c6573b9
